---
title: "CSULA Weather Scraper Notebook"
---

## Finding and opening the most recent CSV file

```{r}
newestFilename <- list.files("../output", pattern="\\.csv$") %>%
                  sort(decreasing = TRUE) %>%
                  { paste0("../output/", .[1]) }
```

## Read the CSV into a data frame
```{r}
df <- read.csv(newestFilename)
```

## Convert columns with character times in UTC to POSIXct in local time:
```{r}
timeCols <- str_match(names(df), ".+_(at|time)$") %>% { .[,1] } %>% .[!is.na(.)]
df[timeCols] <- lapply(df[timeCols], function (x) as.POSIXct(x, format="%Y-%m-%d %H:%M:%S", tz="UTC"))
df[timeCols] <- lapply(df[timeCols],
  function (x) {
    attr(x, "tzone") <- "America/Los_Angeles"
    x
  })
```


## Plot the temperature & humidity
```{r}
timestampFirst <- min(df$sensor_values_updated_at, na.rm=TRUE)
timestampLast <- max(df$sensor_values_updated_at, na.rm=TRUE)

plotTitle <- paste("CSULA Weather", timestampFirst, "-", timestampLast)
plot(df$sensor_values_updated_at, df$sensor_temp_f,
  main=plotTitle, ylab="Temperature", xlab="Timestamp", type="b", col="red")
par(new=TRUE)
plot(df$sensor_values_updated_at, df$sensor_hum_pct, axes=FALSE, type="b", col="green", ylab="", xlab="")
axis(side=4)
mtext("Humidity", side=4)
```

